name: flutter_application_assignment
description: A Flutter project.

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  intl: ^0.19.0
